# Generated by Django 4.2.7 on 2024-01-07 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("", "Select Account Type"),
                    ("tier1", "Tier1"),
                    ("tier2", "Tier2"),
                    ("tier3", "Tier3"),
                    ("merchant", "Merchant"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("", "Select Account Verification Status..."),
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("owner", "account_no")},
        ),
    ]
