# Generated by Django 3.2.13 on 2022-05-07 23:19

import apps.common.custom_validator
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('account_no', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('identity_verification', models.FileField(help_text='upload a legal document that truely identifies you for verification', unique=True, upload_to='', validators=[apps.common.custom_validator.file_validation])),
                ('verification_status', models.CharField(choices=[('failed', 'Failed'), ('success', 'Success'), ('pending', 'Pending')], default='Pending', max_length=50)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account_type.accounttype')),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
            },
        ),
    ]
