# Generated by Django 3.2.13 on 2022-05-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_auto_20220505_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='date_opened',
            new_name='date_created',
        ),
    ]
