# Generated by Django 3.2.13 on 2022-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_auto_20220509_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
