# Generated by Django 3.2.13 on 2022-05-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0005_alter_bankaccount_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='transfer_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
