# Generated by Django 4.2.7 on 2024-01-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthOtp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("otp", models.CharField(default=None, max_length=255)),
                ("expiry", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("account verification", "Account Verification"),
                            ("user login", "User Login"),
                            ("password reset", "Password Reset"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AuthOtp",
                "verbose_name_plural": "AuthOtps",
            },
        ),
    ]
