# Generated by Django 4.2.7 on 2024-01-07 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0002_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionOtp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("otp", models.CharField(default=None, max_length=255)),
                ("expiry", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("transfer", "Transfer"),
                            ("withdrawal", "Withdrawal"),
                        ]
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transactionotp",
                "verbose_name_plural": "TransanctionOtps",
            },
        ),
    ]
