# Generated by Django 3.2.13 on 2022-05-07 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(7)]),
        ),
    ]
