# Generated by Django 3.2.13 on 2022-05-07 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220507_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(7)]),
        ),
    ]
