# Generated by Django 3.2.13 on 2022-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220503_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-date_created',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('account_office', 'Account Officer'), ('bank_manager', 'Bank Manager'), ('teller', 'Teller')], default='admin', max_length=50),
        ),
    ]
