# Generated by Django 4.1.7 on 2023-03-25 17:16

import apps.cards.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=50,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[apps.cards.models.validate_card_number],
                    ),
                ),
                (
                    "cvv",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        unique=True,
                        validators=[apps.cards.models.validate_cvv],
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
