# Generated by Django 4.2.7 on 2024-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.CharField(
                choices=[("", "Select card type..."), ("debit card", "Debit Card")],
                max_length=50,
            ),
        ),
    ]
