# Generated by Django 4.2.7 on 2024-01-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_account_type_and_more"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="created_on",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_channel",
            field=models.CharField(
                choices=[
                    ("", "Select transaction"),
                    ("deposit", "Deposit"),
                    ("transfer", "Transfer"),
                    ("withdrawal", "Withdrawal"),
                ],
                default="deposit",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_account",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_account",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("", "Select transaction type..."),
                    ("debit", "Debit"),
                    ("credit", "Credit"),
                ],
                default="debit",
                max_length=50,
            ),
        ),
    ]
