# Generated by Django 4.2.7 on 2024-01-25 09:38

import apis.common.custom_validator
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_country_alter_customuser_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[apis.common.custom_validator.file_validator],
                verbose_name="profile_images",
            ),
        ),
    ]
